# DATABASE
spring:
  #H2
  h2:
    console:
      enabled: true
      path: /h2-console #콘솔 url
  datasource:
    url: jdbc:h2:~/local #내가 만든 db경로 + 이름
    driverClassName: org.h2.Driver
    username: sa
    password:
  #JPA
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.H2Dialect